### ISSUE TITLE
Tf crashes after trying to create datadog_logs_metric

### ISSUE THREAD

**Issue by ramirocastillo93** [DataDog/terraform-provider-datadog#1607]
Hey guys,

I'm trying to create a `datadog_logs_metric` resource (actually multiple ones by using the `for_each` option) but, after creation and successful plan, Terraform crashes. I'm supposed to mantain multiple logs metrics, that's why I need to do it this way.

The issue started after I defined the `for_each` option on the deployment `main.tf` file. When I try to create just one, it doesn't crash.

Plan Output
```hcl
 terraform plan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.logs_metric["core-order_1p_nota_credito_metric"].datadog_logs_metric.logs_metric will be created
  + resource "datadog_logs_metric" "logs_metric" {
      + id   = (known after apply)
      + name = "drf_ops.falCORP.core-order.core-order_1p_nota_credito"

      + compute {
          + aggregation_type = "count"
        }

      + filter {
          + query = "service:core-order returnorderupdated eventSubType=refundIdUpdated -@parsedResponse.data.return.returnOrderLines.item.sellerId:(SC*)"
        }

      + group_by {}
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### Terraform Version
```
terraform -v
Terraform v1.3.3
on darwin_amd64
```

### Datadog Plugin Version

`terraform-provider-datadog_v3.16.0`

### Affected Resource(s)

- datadog_logs_metric

### Terraform Configuration Files

modules/log_based_metrics/main.tf
```hcl
resource "datadog_logs_metric" "logs_metric" {
  name = "${var.team}.${var.bu}${var.country}.${var.service}.${var.name}"
  compute {
    aggregation_type = var.compute_aggregation_type
    path             = var.compute_path
  }
  filter {
    query = var.query
  }
  group_by {
    path     = var.group_by_path
    tag_name = var.group_by_tag_name
  }
}
```

modules/log_based_metrics/variables.tf
```hcl
variable "team" {
  type        = string
  description = "The team from which the Logs-Metric is based on"
}

variable "bu" {
  type        = string
  description = "The BU from which the Logs-Metric is based on"
}

variable "name" {
    type = string
    description = "Name of your log metric"
}

variable "service" {
  type        = string
  description = "The name of the service"
}

variable "country" {
  type        = string
  description = "The country from which the Logs-Metric is based on"

  validation {
    condition     = contains(["CL","PE","CO","BR","AR","MX","UY","CORP"], var.country)
    error_message = "Acceptable values are CL, PE, CO, BR, AR, MX, UY, CORP."
  }
}

variable "compute_aggregation_type" {
  type        = string
  description = "Aggregation type. Distribution or count"

  validation {
    condition     = contains(["distribution","count"], var.compute_aggregation_type)
    error_message = "Acceptable values are distribution or count."
  }
}

variable "compute_path" {
  type        = string
  description = "Path of the compute"
  default     = null

#   validation {
#     condition     = can(regex("^distribution"), var.compute_aggregation_type)
#     error_message = "Variable compute_aggregation_type must be distribution."
#   }
}

variable "query" {
  type        = string
  description = "The query from which the logs-metric is going to be created from"
}

variable "group_by_path" {
  type        = string
  description = ""
  default     = null
}

variable "group_by_tag_name" {
  type        = string
  description = ""
  default     = null
}
```

Deployment
```hcl
module "logs_metric" {
  source                   = "../modules/log_based_metrics"
  for_each                 = var.logs_metric_group
  name                     = each.value.name
  team                     = each.value.team
  country                  = each.value.country
  bu                       = each.value.bu
  service                  = each.value.service
  compute_aggregation_type = each.value.compute_aggregation_type
  compute_path             = each.value.compute_path
  query                    = each.value.query
  group_by_path            = each.value.group_by_path
  group_by_tag_name        = each.value.group_by_tag_name
}
```

terraform.tfvars
```hcl
logs_metric_group = {
  core-order_1p_nota_credito_metric = {
    team                     = "drf_ops"
    name                     = "core-order_1p_nota_credito"
    bu                       = "fal"
    service                  = "core-order"
    country                  = "CORP"
    compute_aggregation_type = "count"
    query                    = "service:core-order returnorderupdated eventSubType=refundIdUpdated -@parsedResponse.data.return.returnOrderLines.item.sellerId:(SC*)"
    group_by_path            = ""
    group_by_tag_name        = ""
    compute_path             = ""
  }
}
```

### Debug Output
```
╷
│ Error: Plugin did not respond
│ 
│   with module.logs_metric["core-order_1p_nota_credito_metric"].datadog_logs_metric.logs_metric,
│   on ../modules/log_based_metrics/main.tf line 1, in resource "datadog_logs_metric" "logs_metric":
│    1: resource "datadog_logs_metric" "logs_metric" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-datadog_v3.16.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 26 [running]:
github.com/terraform-providers/terraform-provider-datadog/datadog.getGroupBys(0xc0002f2cb8)
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_logs_metric.go:163 +0x24c
github.com/terraform-providers/terraform-provider-datadog/datadog.buildDatadogLogsMetric(0xc0008b2500)
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_logs_metric.go:121 +0x1a5
github.com/terraform-providers/terraform-provider-datadog/datadog.resourceDatadogLogsMetricCreate({0x2278a20, 0xc0008883c0}, 0xc0002f3030, {0x1d612c0, 0xc00058e6c0})
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_logs_metric.go:182 +0x7d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00034b180, {0x2278a20, 0xc0008883c0}, 0xd, {0x1d612c0, 0xc00058e6c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00034b180, {0x2278a20, 0xc0008883c0}, 0xc0000db5f0, 0xc0000ab200, {0x1d612c0, 0xc00058e6c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:837 +0xc29
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003160f0, {0x2278978, 0xc000574380}, 0xc0009eda40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00044adc0, {0x2278a20, 0xc000881920}, 0xc0001e0c40)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1fc6820, 0xc00044adc0}, {0x2278a20, 0xc000881920}, 0xc000108c00, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032aa80, {0x2287c60, 0xc0000be680}, 0xc0007bf200, 0xc0003f5110, 0x2dc0780, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00032aa80, {0x2287c60, 0xc0000be680}, 0xc0007bf200, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-datadog_v3.16.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

Creation of a Log Metric.

### Actual Behavior

Crashed.

### Steps to Reproduce

1. `terraform apply`

**Comment by nkzou** [comment]
Hi there, thanks for letting us know. We were able to reproduce this bug and identified the issue that leads to the provider crashing.
Something I noticed though - your `logs_metric` module creates empty `group_by` blocks when `group_by_path` and `group_by_tag_name` are both empty strings, which the Datadog backend won't accept. You should instead omit the `group_by` block entirely if both path and tag_name are empty strings. This will also allow you to avoid this bug in the meantime while we push out a fix.
