### ISSUE TITLE
[datadog_service_definition_yaml] panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by marceloboeira** [DataDog/terraform-provider-datadog#1653]
### Terraform Version

```
Terraform v1.3.5
on darwin_amd64
+ provider registry.terraform.io/datadog/datadog v3.18.0
```

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_service_definition_yaml

### Terraform Configuration Files

```hcl
resource "datadog_service_definition_yaml" "service_definition" {
  service_definition = yamlencode({
    "schema-version": "v2",
    "dd-service": "testing",
    "team": "does-it-matter",
    "links": [
      {
        "url": "https://example.com",
        "title": "Email-Templatez Dashboard",
        "type": "link"
      },
      {
        "url": "https://app.datadoghq.com/logs...",
        "title": "logs",
        "type": "link"
      }
    ]
  })
}
```

Please note the `title` should actually be `name` and that is the problem -- however, the fact that this returns a `panic` is concerning.

### Panic Output

```
Stack trace from the terraform-provider-datadog_v3.18.0 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 46 [running]:
github.com/terraform-providers/terraform-provider-datadog/datadog.getNameField(...)
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_service_definition_yaml.go:154
github.com/terraform-providers/terraform-provider-datadog/datadog.normalizeArrayField.func1(0xc000c16bb8?, 0x0?)
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_service_definition_yaml.go:144 +0x165
sort.insertionSort_func({0xc000824a90?, 0xc000c8cf60?}, 0x0, 0x2)
        sort/zfuncversion.go:12 +0xb1
sort.stable_func({0xc000824a90?, 0xc000c8cf60?}, 0x2)
        sort/zfuncversion.go:171 +0x72
sort.SliceStable({0x1e19ea0, 0xc0001232f0}, 0x2?)
        sort/slice.go:32 +0x85
github.com/terraform-providers/terraform-provider-datadog/datadog.normalizeArrayField(0x1ec7460?, {0x21095f9, 0x5})
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_service_definition_yaml.go:143 +0x105
github.com/terraform-providers/terraform-provider-datadog/datadog.prepServiceDefinitionResource(0xc000254dc0?)
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_service_definition_yaml.go:107 +0x290
github.com/terraform-providers/terraform-provider-datadog/datadog.resourceDatadogServiceDefinitionYAML.func2({0x1e5d580?, 0xc000a282d0?})
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_service_definition_yaml.go:71 +0x45
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffString(0x12?, {0x2117ff7, 0x12}, 0xc00078da40, 0xc000824d98, {0x232a248, 0xc000a86480}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/schema.go:1550 +0x103
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0x6?, {0x2328080, 0xc000c8c750}, {0x2117ff7, 0x12}, 0xc00078da40, 0xc000a86400, {0x232a248?, 0xc000a86480}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/schema.go:1129 +0x16b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc000240c90, {0x2328080, 0xc000c8c750}, 0xc000c81790, 0xc000c8cba0, 0xc000144660, {0x1de6d60, 0xc000c68e10}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/schema.go:679 +0x333
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x2328780?, {0x2328080?, 0xc000c8c750?}, 0xc000c81790, 0x1ec7460?, {0x1de6d60?, 0xc000c68e10?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:890 +0x6c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc0001a2018, {0x2328080?, 0xc000c8c600?}, 0xc000afcb40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:741 +0x98c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc0003e20a0, {0x2328080?, 0xc000c78f30?}, 0xc000a15a40)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:783 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x205a0a0?, 0xc0003e20a0}, {0x2328080, 0xc000c78f30}, 0xc000a159d0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:367 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x232ad80, 0xc0007029c0}, 0xc000838000, 0xc0003f9170, 0x2da6e68, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x232ad80, 0xc0007029c0}, 0xc000838000, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-datadog_v3.18.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

A meaningful error message
 
### Actual Behavior

A panic in the terraform plugin

### Steps to Reproduce

1. `terraform plan`

**Comment by marceloboeira** [comment]
I think it's mainly that there is an assumption that the `name` field always exist,... it should be easier to probably define the schema of the JSON/YAML and simplify this whole setup.

https://github.com/DataDog/terraform-provider-datadog/blob/master/datadog/resource_datadog_service_definition_yaml.go#L152-L157
