### ISSUE TITLE
datadog_dashboard_json panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by nevir** [DataDog/terraform-provider-datadog#1897]
When fetching remote state of a dashboard, the provider panics on [this line](https://github.com/DataDog/terraform-provider-datadog/blob/v3.24.0/datadog/resource_datadog_dashboard_json.go#L251) (`attrMap` is `nil`?).

It seems related to/introduced by #1854

### Terraform Version

```
Terraform v1.3.3
on darwin_arm64
+ provider registry.terraform.io/datadog/datadog v3.24.0
+ provider registry.terraform.io/hashicorp/aws v4.65.0
+ provider registry.terraform.io/hashicorp/external v2.3.1
```

### Affected Resource(s)

- datadog_dashboard_json

### Terraform Configuration Files

Unfortunately, I do not have a configuration that I can easily share. However, the error occurs when refreshing remote state, regardless of the local state targets.

### Debug Output

(note that the remote dashboard JSON that's breaking the plugin is in the log output) - dashboard id `tnx-dux-3qs` on `us5`. We're pinning the provider to 3.23.0 to work around this (so the remote state will have changed by the time you look at this)

https://gist.github.com/nevir/e88822c71fceb2b842accd3796730a15

### Panic Output

```
panic: assignment to entry in nil map

goroutine 1039 [running]:
github.com/terraform-providers/terraform-provider-datadog/datadog.prepResource(0x140009f8660?)
	github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_dashboard_json.go:251 +0x11c
github.com/terraform-providers/terraform-provider-datadog/datadog.resourceDatadogDashboardJSON.func2({0x1054e22a0?, 0x140003db0a0?})
	github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_dashboard_json.go:56 +0x80
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffString(0x0?, {0x10512c6f1, 0x9}, 0x14000301540, 0x14000272aa8, {0x1057fb180, 0x14000aeba00}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/schema.go:1550 +0xb4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0x14000272eb8?, {0x1057f7920, 0x140009ea240}, {0x10512c6f1, 0x9}, 0x14000301540, 0x14000aeb980, {0x1057fb180?, 0x14000aeba00}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/schema.go:1129 +0xdc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0x14000692f60, {0x1057f7920, 0x140009ea240}, 0x14000712b60, 0x140009eaf60, 0x1057eb170, {0x105458fc0, 0x1400045c060}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/schema.go:679 +0x2a0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x1057f8020?, {0x1057f7920?, 0x140009ea240?}, 0x14000712b60, 0x10555c280?, {0x105458fc0?, 0x1400045c060?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:890 +0x50
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0x140001a1410, {0x1057f7920?, 0x140009ea120?}, 0x14000ece5a0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:741 +0x838
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.PlanResourceChange({0x140003a4180, 0x140003a41e0, {0x14000a064a0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_PlanResourceChange.go:27 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0x140004a0000, {0x1057f7920?, 0x140009e4de0?}, 0x14000916540)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:783 +0x3b8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x1057302e0?, 0x140004a0000}, {0x1057f7920, 0x140009e4de0}, 0x140009164d0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:367 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000722000, {0x1057fc620, 0x14000682820}, 0x1400058e000, 0x14000a0ede0, 0x10637f088, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xb7c
google.golang.org/grpc.(*Server).handleStream(0x14000722000, {0x1057fc620, 0x14000682820}, 0x1400058e000, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x290
```

### Expected Behavior

No crash

### Actual Behavior

Crash

### Steps to Reproduce

1. `terraform plan`

### References

- #1854

**Comment by skarimo** [comment]
Thanks for the report. I was able to only reproduce this when refreshing the terraform state with an empty dashboard definition such as:
```
resource "datadog_dashboard_json" "foo" {
  dashboard = ""
}
```

Making sure the resource definition is valid should unblock you.

This will be closed by https://github.com/DataDog/terraform-provider-datadog/pull/1898

**Comment by nevir** [comment]
> Making sure the resource definition is valid should unblock you.

Ah, relevant - so this is occurring when the dashboard was removed (but state still existed)
