### ISSUE TITLE
 Terraform Plan is failing with Error: Plugin did not respond || The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call with latest Datadog version (3.26)

### ISSUE THREAD

**Issue by shwetaarshad** [DataDog/terraform-provider-datadog#1971]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

terraform -v
Terraform v1.5.0
on darwin_amd64

provider registry.terraform.io/datadog/datadog v3.26.0

### Affected Resource(s)

Please list the resources as a list, for example:
NA

### Terraform Configuration Files

```terraform {

  required_providers {
    datadog = {
      source = "DataDog/datadog"
    }
  }

  backend "s3" {
    key = "<none set>"
    encrypt = true
  }


}

# Configure the Datadog provider
provider "datadog" {
  api_key = var.datadog_api_key
  app_key = var.datadog_app_key
  api_url = "https://api.datadoghq.com/"
}
```

### Debug Output

Please provide a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

**NOTE:** Remember to review debug output before posting, and redact any sensitive data.

### Panic Output

```
╷
│ Error: Plugin did not respond
│
│ with datadog_synthetics_test.admin_user_can_navigate_console_overview_page,
│ on userNavigatesOverviewPage.tf line 8, in resource "datadog_synthetics_test" "admin_user_can_navigate_console_overview_page":
│ 8: resource "datadog_synthetics_test" "admin_user_can_navigate_console_overview_page" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-datadog_v3.26.0 plugin:

panic: interface conversion: interface {} is nil, not bool

goroutine 171 [running]:
github.com/terraform-providers/terraform-provider-datadog/datadog.updateSyntheticsBrowserTestLocalState(0x238c7e0?, 0xc000fd0ad8)
github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_synthetics_test_.go:2787 +0x2fd4
github.com/terraform-providers/terraform-provider-datadog/datadog.resourceDatadogSyntheticsTestRead({0x2686aa0?, 0xc0011d4ea0?}, 0xc0005ec000, {0x2061da0?, 0xc000c0edb0?})
github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_synthetics_test_.go:1301 +0x986
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000162ee0, {0x2686aa0, 0xc0011d4ea0}, 0xd?, {0x2061da0, 0xc000c0edb0})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000162ee0, {0x2686aa0, 0xc0011d4ea0}, 0xc0002865b0, {0x2061da0, 0xc000c0edb0})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000185b00, {0x2686aa0?, 0xc0011d4d80?}, 0xc00129a440)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0xc0006d9e90, 0xc0006d9ef0, {0xc000885d00, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ReadResource.go:26 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0000015e0, {0x2686aa0?, 0xc0011d4270?}, 0xc0001de4e0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x235a7a0?, 0xc0000015e0}, {0x2686aa0, 0xc0011d4270}, 0xc0001780e0, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000a64000, {0x268bc40, 0xc0001b21a0}, 0xc0012be120, 0xc0009dfb60, 0x32b0a10, 0x0)
google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc000a64000, {0x268bc40, 0xc0001b21a0}, 0xc0012be120, 0x0)
google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-datadog_v3.26.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

The Terraform Plan and Apply should work

### Actual Behavior

The terraform Plan step is failing with plugin error.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform init`
2. `terraform plan`

### Important Factoids

Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

-   GH-1234

**Comment by therve** [comment]
Hi,

Can you describe your terraform config and more context around the error? Thanks.
