### ISSUE TITLE
interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by dannyrife** [DataDog/terraform-provider-datadog#2303]
### Datadog Terraform Provider Version

v3.33.0+

### Terraform Version

v1.3.7

### What resources or data sources are affected?

resource_datadog_monitor

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "monitor" {
  count                    = var.monitor_count
  escalation_message       = var.escalation_message
  evaluation_delay         = var.evaluation_delay
  force_delete             = var.force_delete
  group_retention_duration = var.group_retention_duration
  include_tags             = var.include_tags
  locked                   = var.locked
  message                  = coalesce(var.message, local.default_messages["default"])
  monitor_threshold_windows {
    recovery_window = var.monitor_threshold_windows.recovery_window
    trigger_window  = var.monitor_threshold_windows.trigger_window
  }
  monitor_thresholds {
    critical          = try(var.monitor_thresholds.critical, null)
    critical_recovery = try(var.monitor_thresholds.critical_recovery, null)
    ok                = try(var.monitor_thresholds.ok, null)
    unknown           = try(var.monitor_thresholds.unknown, null)
    warning           = try(var.monitor_thresholds.warning, null)
    warning_recovery  = try(var.monitor_thresholds.warning_recovery, null)
  }
  name                     = var.name
  new_group_delay          = var.new_group_delay
  no_data_timeframe        = var.no_data_timeframe
  notification_preset_name = var.notification_preset_name
  notify_audit             = var.notify_audit
  notify_by                = var.notify_by
  notify_no_data           = var.notify_no_data
  on_missing_data          = var.on_missing_data
  priority                 = var.priority
  query                    = var.query
  renotify_interval        = var.renotify_interval
  renotify_occurrences     = var.renotify_occurrences
  renotify_statuses        = var.renotify_statuses
  require_full_window      = var.require_full_window
  restricted_roles         = var.restricted_roles
  scheduling_options {
    evaluation_window {
      hour_starts  = try(var.scheduling_options.evaluation_window.hour_starts, null)
      day_starts   = try(var.scheduling_options.evaluation_window.day_starts, null)
      month_starts = try(var.scheduling_options.evaluation_window.month_starts, null)
    }
  }
  tags      = local.tags
  timeout_h = var.timeout_h
  type      = var.type
  validate  = var.validate
}
```

### Relevant debug or panic output

Stack trace from the terraform-provider-datadog_v3.37.0 plugin:
```
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 45 [running]:
github.com/terraform-providers/terraform-provider-datadog/datadog.buildMonitorStruct({0x101bdb6e0, 0x14000367d40})
	github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_monitor.go:604 +0x26b8
github.com/terraform-providers/terraform-provider-datadog/datadog.resourceDatadogMonitorCustomizeDiff({0x101bde7e0, 0x14000790e10}, 0x14000367d40, {0x1017e03c0?, 0x140007a9290})
	github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_monitor.go:880 +0xb4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0x14000174810, {0x101bde7e0, 0x14000790e10}, 0x14000498c30, 0x14000174210, 0x101bd1f88, {0x1017e03c0, 0x140007a9290}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/schema.go:698 +0x3c4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x14000306380?, {0x101bde7e0?, 0x14000790e10?}, 0x14000498c30, 0x1018fbca0?, {0x1017e03c0?, 0x140007a9290?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:917 +0x9c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0x140003408d0, {0x101bde7e0?, 0x140007904b0?}, 0x14001071a40)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:744 +0x838
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.PlanResourceChange({0x14000227e00, 0x14000227e60, {0x140007998a0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_PlanResourceChange.go:27 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0x140001ba780, {0x101bde7e0?, 0x14000d78090?}, 0x1400055c620)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:786 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x101afc820?, 0x140001ba780}, {0x101bde7e0, 0x14000d78090}, 0x1400055c5b0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:404 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002801e0, {0x101be40e0, 0x14000003380}, 0x1400032f320, 0x140003de0f0, 0x102900c48, 0x0)
	google.golang.org/grpc@v1.56.3/server.go:1335 +0xc90
google.golang.org/grpc.(*Server).handleStream(0x140002801e0, {0x101be40e0, 0x14000003380}, 0x1400032f320, 0x0)
	google.golang.org/grpc@v1.56.3/server.go:1712 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.3/server.go:947 +0xb4
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.56.3/server.go:958 +0x174

Error: The terraform-provider-datadog_v3.37.0 plugin crashed!
```

### Expected Behavior

Previously when we pass in no value for scheduling_options it created an empty scheduling_options block with out issue.  

### Actual Behavior

panic: interface conversion: interface {} is nil, not map[string]interface {}

### Steps to Reproduce

Create a monitor like below and it will crash with this error, not we don't do this directly but in a shared monitor module that is used by developers.
```
resource "datadog_monitor" "reproduce_error" {
  name              = "test_name"
  query               = "sum(current_1mo):datadog.estimated_usage.containers{*} > 0"

  message = "test message"
  type    = "metric alert"

  scheduling_options {
    evaluation_window {
      hour_starts = null
      day_starts   = null
      month_starts =  null
    }
  }
}

```
with the `panic: interface conversion: interface {} is nil, not map[string]interface {}`

### Important Factoids

Seems to be due to this change:
https://github.com/DataDog/terraform-provider-datadog/compare/v3.32.0...v3.33.0#diff-91bf4db4b1e70bf00cf2d6e0eef2b60dde00caa22b8057c9ba26a80d4a280d4bR263-R274

**Comment by dannyrife** [comment]
Update, so the underlying issue is that before the block
```
scheduling_options {
  evaluation_window {}
}
```
was valid and now it is not, I've switched our local usage to use a dynamic block for scheduling options to avoid this.  Still this was not expected in a minor version update since it wasn't backwards compatible.
