### ISSUE TITLE
Cannot create Datadog Dashboard when inserting Powerpack

### ISSUE THREAD

**Issue by PLBU** [DataDog/terraform-provider-datadog#2589]
### Datadog Terraform Provider Version

v3.44.1

### Terraform Version

1.6.6

### What resources or data sources are affected?

resource_datadog_dashboard

### Relevant debug or panic output

https://gist.github.com/PLBU/55c0968e0e838083da17527f6f3bec9b

### Expected Behavior

The Datadog Dashboard should be created successfully. The powerpack is already created. But the datadog_dashboard cannot be created because this?
```
panic: runtime error: index out of range [0] with length 0
```

### Steps to Reproduce

1. terraform apply

**Comment by gnuyent** [comment]
I'm seeing the same issue on Terraform v1.12.2 and `terraform-provider-datadog_v3.70.0`.

Stack trace:
```
Stack trace from the terraform-provider-datadog_v3.70.0 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 5 [running]:
github.com/terraform-providers/terraform-provider-datadog/datadog.buildDatadogPowerpackDefinition(0x14000a57c20)
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_dashboard.go:8776 +0x5b8
github.com/terraform-providers/terraform-provider-datadog/datadog.buildDatadogWidget(0x14000a576b0)
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_dashboard.go:1357 +0x1348
github.com/terraform-providers/terraform-provider-datadog/datadog.buildDatadogWidgets(0x140014e0938)
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_dashboard.go:1206 +0xc8
github.com/terraform-providers/terraform-provider-datadog/datadog.buildDatadogDashboard(0x14001982000)
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_dashboard.go:374 +0x424
github.com/terraform-providers/terraform-provider-datadog/datadog.resourceDatadogDashboardUpdate({0x1066e7008?, 0x14001589080?}, 0x14001982000, {0x1060f44c0?, 0x140002625d0})
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_dashboard.go:202 +0x10c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x140001d1a00, {0x1066e7008, 0x14001589080}, 0x14001982000, {0x1060f44c0, 0x140002625d0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.37.0/helper/schema/resource.go:883 +0xe4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140001d1a00, {0x1066e7008, 0x14001589080}, 0x140004cb790, 0x140006b27e0, {0x1060f44c0, 0x140002625d0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.37.0/helper/schema/resource.go:990 +0x6cc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000143800, {0x1066e7008?, 0x14001588fc0?}, 0x14000b90e60)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.37.0/helper/schema/grpc_provider.go:1484 +0xd88
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x140002ce680, {0x1066e7008?, 0x14001588cf0?}, 0x14000b90e60)
        github.com/hashicorp/terraform-plugin-mux@v0.20.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140002de5a0, {0x1066e7008?, 0x140015881e0?}, 0x1400068f780)
        github.com/hashicorp/terraform-plugin-go@v0.28.0/tfprotov5/tf5server/server.go:941 +0x2a8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1066281c0, 0x140002de5a0}, {0x1066e7008, 0x140015881e0}, 0x1400068f700, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.28.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:687 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002c2200, {0x1066e7008, 0x14001588150}, 0x14001c808a0, 0x140003c45a0, 0x107958708, 0x0)
        google.golang.org/grpc@v1.72.2/server.go:1405 +0xca8
google.golang.org/grpc.(*Server).handleStream(0x140002c2200, {0x1066e7950, 0x14000478000}, 0x14001c808a0)
        google.golang.org/grpc@v1.72.2/server.go:1815 +0x910
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.72.2/server.go:1035 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 39
        google.golang.org/grpc@v1.72.2/server.go:1046 +0x13c
```
