### ISSUE TITLE
Plugin error when trying to create a datadog_webhook resource.

### ISSUE THREAD

**Issue by cphenry** [DataDog/terraform-provider-datadog#2676]
### Datadog Terraform Provider Version

3.44.1

### Terraform Version

v1.9.8

### What resources or data sources are affected?

resource_datadog_webhook

### Terraform Configuration Files

```hcl
resource "datadog_webhook" "prism-alerts" {
  name = "Prism-Alerts"
  url  = "https://webexapis.com/v1/webhooks/incoming/Y2lzY29zcGFyazovL3VzL1dFQkhPT0svMmEzNGNlODgtYzVjYy00MWIyLTk5YTUtZDA0ZDM5YTJhMjVm"
}
```

### Relevant debug or panic output

│ Error: Request cancelled
│ 
│   with datadog_webhook.prism-dd-nonprod-alerts,
│   on main.tf line 25, in resource "datadog_webhook" "prism-dd-nonprod-alerts":
│   25: resource "datadog_webhook" "prism-dd-nonprod-alerts" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-datadog_v3.44.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14aa8bb]

goroutine 107 [running]:
github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider.(*webhookResource).buildWebhookRequestBody(0xc0008e3348?, {0x0?, 0x1c6f3d8?}, 0xc0004d47e0)
        github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider/resource_datadog_webhook.go:247 +0x17b
github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider.(*webhookResource).Create(0xc00018d860, {0x1c693c0, 0xc000725bf0}, {{{{0x1c6f3d8, 0xc0008d4810}, {0x16bdd20, 0xc0008d4780}}, {0x1c71a68, 0xc0009fc8c0}}, {{{0x1c6f3d8, ...}, ...}, ...}, ...}, ...)
        github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider/resource_datadog_webhook.go:128 +0x16c
github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider.(*FrameworkResourceWrapper).Create(0x0?, {0x1c693c0?, 0xc000725bf0?}, {{{{0x1c6f3d8, 0xc0008d4810}, {0x16bdd20, 0xc0008d4780}}, {0x1c71a68, 0xc0009fc8c0}}, {{{0x1c6f3d8, ...}, ...}, ...}, ...}, ...)
        github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider/framework_provider.go:526 +0x5a
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc0001f91e0, {0x1c693c0, 0xc000725bf0}, 0xc000a071f0, 0xc000a071c8)
        github.com/hashicorp/terraform-plugin-framework@v1.3.3/internal/fwserver/server_createresource.go:101 +0x578
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc0001f91e0, {0x1c693c0, 0xc000725bf0}, 0xc0008e2e60, 0xc000a072e0)
        github.com/hashicorp/terraform-plugin-framework@v1.3.3/internal/fwserver/server_applyresourcechange.go:57 +0x4aa
github.com/hashicorp/terraform-plugin-framework/internal/proto5server.(*Server).ApplyResourceChange(0xc0001f91e0, {0x1c693c0?, 0xc000725ad0?}, 0xc0008e2dc0)
        github.com/hashicorp/terraform-plugin-framework@v1.3.3/internal/proto5server/server_applyresourcechange.go:55 +0x38e
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc000329260, 0xc0003292c0, {0xc00057f100, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0xf3
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000322f00, {0x1c693c0?, 0xc000724ba0?}, 0xc0002ae930)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:821 +0x548
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x18e09c0, 0xc000322f00}, {0x1c693c0, 0xc000724ba0}, 0xc0002ae8c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000660000, {0x1c703e0, 0xc0007bc000}, 0xc0004d0000, 0xc0008b9740, 0x2acbec0, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1335 +0xdb8
google.golang.org/grpc.(*Server).handleStream(0xc000660000, {0x1c703e0, 0xc0007bc000}, 0xc0004d0000, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1712 +0x9da
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.3/server.go:947 +0xaf
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 8
        google.golang.org/grpc@v1.56.3/server.go:958 +0x136

Error: The terraform-provider-datadog_v3.44.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

Resource should have been created. 

### Actual Behavior

Resource wasn't created.  Plugin crashed. 

### Steps to Reproduce

terraform apply the code snippet above.

**Comment by nkzou** [comment]
Hi, this should be resolved with version 3.49.0 of the provider. Thanks for reporting!

**Comment by gpkc** [comment]
@nkzou I am getting the error when updating a `datadog_webhook` on 3.49.0. I'm simply trying to remove a property from the `payload` property:

```
resource "datadog_webhook" "webhook" {
  name = "Discord"
  url  = "..."

  payload = jsonencode(
    {
    "embeds":[
        {
            "title":"$EVENT_TITLE",
            "description":"$EVENT_MSG",    # <<<<------ removing this
            "url":"$LINK",
            "color":"3407966",
            "image":{
                "url":"$SNAPSHOT"
            }
        }
    ]
    }
  )
}
```

results in:

```
datadog_webhook.webhook: Modifying... [id=Discord]
╷
│ Error: Plugin did not respond
│ 
│   with datadog_webhook.webhook,
│   on webhook.tf line 1, in resource "datadog_webhook" "webhook":
│    1: resource "datadog_webhook" "webhook" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs
│ may contain more details.
╵

Stack trace from the terraform-provider-datadog_v3.49.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x105b1990c]

goroutine 113 [running]:
github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider.(*webhookResource).buildWebhookUpdateRequestBody(0x140006aae48?, {0x0?, 0x105ffeb20?}, 0x1400040ea20)
        github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider/resource_datadog_webhook.go:268 +0x1fc
github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider.(*webhookResource).Update(0x1400000d938, {0x106331e58, 0x1400084c780}, {{{{0x106337e58, 0x1400084d140}, {0x105ffeb20, 0x1400084d080}}, {0x10633a408, 0x1400036fd60}}, {{{0x106337e58, ...}, ...}, ...}, ...}, ...)
        github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider/resource_datadog_webhook.go:162 +0x194
github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider.(*FrameworkResourceWrapper).Update(0x14000900038?, {0x106331e58?, 0x1400084c780?}, {{{{0x106337e58, 0x1400084d140}, {0x105ffeb20, 0x1400084d080}}, {0x10633a408, 0x1400036fd60}}, {{{0x106337e58, ...}, ...}, ...}, ...}, ...)
        github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider/framework_provider.go:537 +0x60
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).UpdateResource(0x1400016b4a0, {0x106331e58, 0x1400084c780}, 0x1400042f0f8, 0x1400042f0d0)
        github.com/hashicorp/terraform-plugin-framework@v1.3.3/internal/fwserver/server_updateresource.go:122 +0x53c
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x1400016b4a0, {0x106331e58, 0x1400084c780}, 0x140006aa500, 0x1400042f2c0)
        github.com/hashicorp/terraform-plugin-framework@v1.3.3/internal/fwserver/server_applyresourcechange.go:102 +0x118
github.com/hashicorp/terraform-plugin-framework/internal/proto5server.(*Server).ApplyResourceChange(0x1400016b4a0, {0x106331e58?, 0x1400084c690?}, 0x140006aa460)
        github.com/hashicorp/terraform-plugin-framework@v1.3.3/internal/proto5server/server_applyresourcechange.go:55 +0x2e0
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0x140002974a0, 0x14000297500, {0x14000d7a1c0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14000cd40a0, {0x106331e58?, 0x1400010f8f0?}, 0x140001d2150)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:821 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1062369c0, 0x14000cd40a0}, {0x106331e58, 0x1400010f8f0}, 0x140001d20e0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000020000, {0x106338e00, 0x14000118340}, 0x14000404000, 0x1400099dec0, 0x1071c9a20, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1335 +0xb90
google.golang.org/grpc.(*Server).handleStream(0x14000020000, {0x106338e00, 0x14000118340}, 0x14000404000, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1712 +0x7ac
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.3/server.go:947 +0xac
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 71
        google.golang.org/grpc@v1.56.3/server.go:958 +0x14c

Error: The terraform-provider-datadog_v3.49.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
